# Generated by Django 2.2.11 on 2021-05-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='iso2',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='destination',
            name='iso3',
            field=models.CharField(default='', max_length=3),
        ),
    ]
