# Generated by Django 2.2.11 on 2021-05-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20210517_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='img',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='offer',
        ),
        migrations.AddField(
            model_name='destination',
            name='img1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='destination',
            name='img2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='destination',
            name='img3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='destination',
            name='img4',
            field=models.TextField(default=''),
        ),
    ]
